<?php
if (session_status() === PHP_SESSION_NONE) { session_start(); }
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    http_response_code(403); die('Forbidden');
}

// Must arrive via POST and have session data
if ($_SERVER['REQUEST_METHOD'] !== 'POST' || empty($_SESSION['progress_report'])) {
    header('Location: admin_progress_report.php'); exit;
}

require 'db_configuration.php';
require 'sendemail.php';

$conn = new mysqli(DATABASE_HOST, DATABASE_USER, DATABASE_PASSWORD, DATABASE_DATABASE);
if ($conn->connect_error) { die('DB connection failed: ' . $conn->connect_error); }

$data        = $_SESSION['progress_report'];
$courseName  = $data['courseName'];
$assignments = $data['assignments'];
$students    = $data['students'];
$emailMode   = $data['emailMode'];
$tempFile    = $data['tempFile'] ?? '';

$adminEmail  = 'ICS499.LearnandHelp.2026@gmail.com';

// ── Build HTML report for one student ────────────────────────────────────────
function buildReportHtml($courseName, $studentName, $assignments, $scores, $emailMode) {
    $devNotice = '';
    if ($emailMode === 'DEV') {
        $devNotice = '<p style="background:#fff3e0;color:#e65100;padding:10px 16px;border-radius:6px;font-weight:700;margin-bottom:20px;">
            ⚠ DEV MODE — This is a test email. In production this report would be sent to the student\'s parents.</p>';
    }

    $rows = '';
    foreach ($assignments as $a) {
        $val   = trim($scores[$a['index']] ?? '');
        $isBad = ($val === '' || $val === '0');
        $bg    = $isBad ? 'background:#ffe6e6;' : '';
        $fw    = $isBad ? 'font-weight:700;color:#d32f2f;' : '';
        $display = $val === '' ? '<em style="color:#d32f2f;">Missing</em>' : htmlspecialchars($val);
        $rows .= '<tr>
            <td style="padding:9px 14px;border-bottom:1px solid #e0e0e0;' . $bg . $fw . '">' . htmlspecialchars($a['name']) . '</td>
            <td style="padding:9px 14px;border-bottom:1px solid #e0e0e0;' . $bg . '">' . htmlspecialchars($a['date']) . '</td>
            <td style="padding:9px 14px;border-bottom:1px solid #e0e0e0;text-align:center;' . $bg . '">' . htmlspecialchars($a['points']) . '</td>
            <td style="padding:9px 14px;border-bottom:1px solid #e0e0e0;text-align:center;' . $bg . $fw . '">' . $display . '</td>
        </tr>';
    }

    return '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f8f8f8;">
    <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8f8f8;padding:30px 0;">
      <tr><td align="center">
        <table width="800" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 4px 20px rgba(0,0,0,.10);">
          <!-- Header -->
          <tr><td style="background:#1a1a1a;padding:28px 36px;">
            <span style="font-size:1.6rem;font-weight:900;color:#99D930;letter-spacing:1px;">Learn</span>
            <span style="font-size:1.6rem;font-weight:900;color:#fff;"> and </span>
            <span style="font-size:1.6rem;font-weight:900;color:#99D930;">Help</span>
            <span style="font-size:0.95rem;color:#aaa;margin-left:14px;">Progress Report</span>
          </td></tr>
          <!-- Body -->
          <tr><td style="padding:28px 36px;">
            ' . $devNotice . '
            <p style="margin:0 0 4px;color:#555;font-size:0.9rem;">Course</p>
            <p style="margin:0 0 20px;font-size:1.25rem;font-weight:700;color:#1a1a1a;">' . htmlspecialchars($courseName) . '</p>
            <p style="margin:0 0 4px;color:#555;font-size:0.9rem;">Student</p>
            <p style="margin:0 0 24px;font-size:1.1rem;font-weight:700;color:#1a1a1a;">' . htmlspecialchars($studentName) . '</p>

            <table width="100%" cellpadding="0" cellspacing="0" style="border-collapse:collapse;font-size:0.9rem;">
              <thead>
                <tr style="background:#1a1a1a;color:#fff;">
                  <th style="padding:10px 14px;text-align:left;">Assignment</th>
                  <th style="padding:10px 14px;text-align:left;">Due Date</th>
                  <th style="padding:10px 14px;text-align:center;">Points</th>
                  <th style="padding:10px 14px;text-align:center;">Score</th>
                </tr>
              </thead>
              <tbody>' . $rows . '</tbody>
            </table>

            <p style="margin-top:28px;font-size:0.85rem;color:#888;">
              This report was generated by Learn and Help. Please do not reply to this email.
            </p>
          </td></tr>
          <!-- Footer -->
          <tr><td style="background:#1a1a1a;padding:16px 36px;text-align:center;">
            <span style="color:#99D930;font-weight:700;font-size:0.9rem;">learnandhelp.com</span>
          </td></tr>
        </table>
      </td></tr>
    </table>
    </body></html>';
}

// ── Determine scope: individual or all ───────────────────────────────────────
$singleIndex = isset($_POST['student_index']) && $_POST['student_index'] !== ''
    ? (int)$_POST['student_index']
    : null;

$isSingleSend = $singleIndex !== null;
$queue        = $isSingleSend ? [$singleIndex => $students[$singleIndex]] : $students;

// ── Send loop ─────────────────────────────────────────────────────────────────
$results = [];

foreach ($queue as $s) {
    $subject  = 'Progress Report – ' . $courseName . ' – ' . $s['fullName'];
    $htmlBody = buildReportHtml($courseName, $s['fullName'], $assignments, $s['scores'], $emailMode);

    if ($emailMode === 'DEV') {
        $sent = sendProgressReport([$adminEmail], null, '[DEV] ' . $subject, $htmlBody);
        $results[] = [
            'name'    => $s['fullName'],
            'email'   => $s['email'],
            'matched' => $s['matched'],
            'sentTo'  => $adminEmail . ' (DEV)',
            'ok'      => $sent,
        ];
    } elseif ($s['matched'] && (!empty($s['recipients']) || !empty($s['studentEmail']))) {
        $toList = array_unique(array_filter(array_map('trim',
            array_merge($s['recipients'], [$s['studentEmail']])
        )));
        $sent = sendProgressReport($toList, $adminEmail, $subject, $htmlBody);
        $results[] = [
            'name'    => $s['fullName'],
            'email'   => $s['email'],
            'matched' => true,
            'sentTo'  => implode(', ', $toList),
            'ok'      => $sent,
        ];
    } else {
        $results[] = [
            'name'    => $s['fullName'],
            'email'   => $s['email'],
            'matched' => $s['matched'],
            'sentTo'  => '',
            'ok'      => null,
        ];
    }
}

// Clean up only on Send All — keep session alive for individual sends
if (!$isSingleSend) {
    if (!empty($tempFile) && file_exists($tempFile)) { @unlink($tempFile); }
    unset($_SESSION['progress_report']);
}
$conn->close();
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Progress Report Results | Admin</title>
  <link rel="icon" href="images/icon_logo.png" type="image/icon type">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700;900&display=swap" rel="stylesheet">
  <link href="css/main.css?v=2025-08-22a" rel="stylesheet">
  <style>
    :root { --accent: #99D930; }
    body { margin: 0; font-family: 'Montserrat', sans-serif; background: #f8f8f8; color: #252525; overflow-x: hidden; }
    .intro-banner { background: #1a1a1a; color: #fff; text-align: center; padding: 24px 20px 20px; }
    .intro-banner h1 { font-size: 3rem; font-weight: 900; margin: 0; }
    .accent-text { color: var(--accent); }
    .page-wrap { max-width: 1100px; margin: 40px auto; padding: 0 20px; }
    .card { background: #fff; border-radius: 14px; box-shadow: 0 4px 24px rgba(0,0,0,.08); padding: 36px; margin-bottom: 30px; }

    .mode-badge { display: inline-block; padding: 4px 16px; border-radius: 20px; font-weight: 700; font-size: 0.9rem; margin-left: 12px; vertical-align: middle; }
    .mode-dev  { background: #e65100; color: #fff; }
    .mode-prod { background: #2e7d32; color: #fff; }

    .results-table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 0.9rem; }
    .results-table th { background: #1a1a1a; color: #fff; padding: 10px 12px; text-align: left; white-space: nowrap; }
    .results-table td { padding: 9px 12px; border-bottom: 1px solid #e0e0e0; vertical-align: middle; }
    .results-table tr:hover td { background: #f8f8f8; }
    .check  { color: #2e7d32; font-weight: 700; }
    .cross  { color: #d32f2f; font-weight: 700; }
    .skip   { color: #999; }

    .summary-row { display: flex; gap: 28px; margin-bottom: 24px; flex-wrap: wrap; }
    .summary-box { background: #f4f4f4; border-radius: 10px; padding: 16px 24px; min-width: 130px; text-align: center; }
    .summary-box .num { font-size: 2rem; font-weight: 900; color: #1a1a1a; }
    .summary-box .lbl { font-size: 0.8rem; color: #666; font-weight: 700; text-transform: uppercase; margin-top: 4px; }
    .num-sent   { color: #2e7d32 !important; }
    .num-fail   { color: #d32f2f !important; }
    .num-skip   { color: #999 !important; }

    .btn { padding: 12px 32px; border: none; border-radius: 8px; font-size: 1rem; font-weight: 700; font-family: 'Montserrat', sans-serif; cursor: pointer; transition: all 0.2s; text-decoration: none; display: inline-block; }
    .btn-primary { background: var(--accent); color: #252525; }
    .btn-primary:hover { background: #8cc428; transform: translateY(-2px); }
  </style>
</head>
<body>
<?php include 'show-navbar.php'; show_navbar(); ?>

<section class="intro-banner">
  <h1>Progress <span class="accent-text">Report</span></h1>
</section>

<div class="page-wrap">
  <div class="card">
    <h2 style="margin-top:0;">Send Results — <?= htmlspecialchars($courseName) ?>
      <span class="mode-badge <?= $emailMode === 'DEV' ? 'mode-dev' : 'mode-prod' ?>">
        <?= htmlspecialchars($emailMode) ?> MODE
      </span>
    </h2>

    <?php
    $sentCount   = count(array_filter($results, fn($r) => $r['ok'] === true));
    $failCount   = count(array_filter($results, fn($r) => $r['ok'] === false));
    $skipCount   = count(array_filter($results, fn($r) => $r['ok'] === null));
    ?>
    <div class="summary-row">
      <div class="summary-box"><div class="num num-sent"><?= $sentCount ?></div><div class="lbl">Sent</div></div>
      <div class="summary-box"><div class="num num-fail"><?= $failCount ?></div><div class="lbl">Failed</div></div>
      <div class="summary-box"><div class="num num-skip"><?= $skipCount ?></div><div class="lbl">Skipped</div></div>
      <div class="summary-box"><div class="num"><?= count($results) ?></div><div class="lbl">Total</div></div>
    </div>

    <?php if ($emailMode === 'DEV'): ?>
      <p style="color:#e65100;font-weight:600;margin-bottom:16px;">
        ⚠ DEV mode — all emails were delivered only to the admin address.
      </p>
    <?php endif; ?>

    <div style="overflow-x:auto;">
    <table class="results-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Student Name</th>
          <th>CSV Email</th>
          <th>Matched?</th>
          <th>Sent To</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($results as $i => $r): ?>
        <tr>
          <td><?= $i + 1 ?></td>
          <td><?= htmlspecialchars($r['name']) ?></td>
          <td><?= htmlspecialchars($r['email']) ?></td>
          <td>
            <?php if ($r['matched']): ?>
              <span class="check">&#10003; Yes</span>
            <?php else: ?>
              <span class="cross">&#10007; No match</span>
            <?php endif; ?>
          </td>
          <td style="font-size:0.82rem;color:#555;"><?= htmlspecialchars($r['sentTo']) ?></td>
          <td>
            <?php if ($r['ok'] === true): ?>
              <span class="check">&#10003; Sent</span>
            <?php elseif ($r['ok'] === false): ?>
              <span class="cross">&#10007; Failed</span>
            <?php else: ?>
              <span class="skip">&#8212; Skipped</span>
            <?php endif; ?>
          </td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
    </div>

    <div style="margin-top:28px;display:flex;gap:16px;align-items:center;">
      <?php if ($isSingleSend): ?>
        <a href="admin_progress_report.php" class="btn btn-primary">&#8592; Back to Preview</a>
      <?php else: ?>
        <a href="admin_progress_report.php" class="btn btn-primary">&#8592; Upload Another Report</a>
      <?php endif; ?>
    </div>
  </div>
</div>
<?php include 'footer.php'; ?>
</body>
</html>
